[project]
name = "qsao"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.0",
    "pyxlsb>=1.0.10",
    "scikit-learn>=1.8.0",
]
